# Site settings
title: AI
email: karpathy@cs.stanford.edu
description: "Artificial Intelligence"
baseurl: ""
url: "http://b-area.github.io"

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
